import type { Workspace } from './types';
import { Badge, Empty, Heading, money } from './ui';
import { EvidenceBundle, type Bundle } from './EvidenceBundle';
import { workspaceLink } from './ledger';

export function Activity({ data, loadEvidence }: { data: Workspace; loadEvidence?: () => Promise<Bundle> }) {
  return <>
    <Heading eyebrow="THE DURABLE RECORD" title="History">Read back what was approved, what the provider confirmed, and what remains unknown.</Heading>
    {data.receipts.length ? <section className="decision-outcome" aria-label="Recorded collection outcome"><p className="eyebrow">{data.live?.mail ? 'SAVED DECISION · AMAZON SES' : 'SAVED DECISION · SIMULATED OUTBOX'}</p><h2>Read back the result before doing anything else</h2><p>The latest recorded attempt is {data.receipts.at(-1)!.state} for {data.receipts.at(-1)!.invoice_id}. {data.live?.mail ? 'Inspect provider evidence below. Approving a chase does not reduce the amount owed.' : 'No real email was sent, and approving a chase does not reduce the amount owed.'}</p><a className="secondary" href={workspaceLink(data.receipts.at(-1)!.invoice_id)}>Return to this collection case →</a></section> : null}
    <EvidenceBundle revision={data.revision} load={loadEvidence} />
    <div className="notice"><strong>{data.live?.mail ? 'Session provider: controlled Amazon SES' : 'Session provider: simulated outbox'}</strong><p>Provider acceptance is not delivery. {data.live?.mail ? 'This session can send real email after explicit approval of the exact draft to the verified test recipient. Arrival remains unproven in this session record.' : 'This session records simulated sends only. Current provider availability does not convert its saved receipts into real email.'}</p></div>
    <section className="panel"><div className="panel-heading"><h2>Delivery receipts <span className="count">{data.receipts.length}</span></h2></div>{data.receipts.length ? <div className="receipt-list">{data.receipts.map(receipt => <article key={receipt.fingerprint}><div className="flex flex-wrap items-center justify-between gap-3"><h3>{receipt.invoice_id} · {money(receipt.amount)}</h3><Badge tone="blue">{data.live?.mail ? 'SES' : 'Simulated'} · {receipt.state}</Badge></div><p>{receipt.to_address}</p><dl><dt>Receipt ID</dt><dd>{receipt.message_id ?? 'No provider identifier'}</dd><dt>Recorded</dt><dd>{receipt.at}</dd><dt>Arrival</dt><dd>{data.live?.mail ? 'Unproven unless separately confirmed by delivery evidence' : 'Unproven · no real email sent'}</dd></dl>{receipt.error ? <p role="alert">{receipt.error}</p> : null}<details><summary>Approved content fingerprint</summary><code className="fingerprint">{receipt.fingerprint}</code></details></article>)}</div> : <Empty title="No delivery attempts">{data.live?.mail ? 'Approving an exact draft creates a real SES attempt here.' : 'Approving an exact draft creates a simulated receipt here.'} Reading or drafting alone never sends.</Empty>}</section>
    <section className="panel"><div className="panel-heading"><h2>What each receipt state means</h2></div><dl className="state-key">{Object.entries(data.receipt_states).map(([state, explanation]) => <div key={state}><dt><Badge>{state}</Badge></dt><dd>{explanation}</dd></div>)}</dl></section>
    <section className="panel"><div className="panel-heading"><h2>Workspace history</h2><span className="muted">Latest first</span></div>{data.activity.length ? <ol className="timeline">{[...data.activity].reverse().map(event => <li key={event.id}><span className="timeline-dot" aria-hidden="true" /><div><h3>{event.title}</h3><p>{event.detail}</p><time>{event.at}</time></div></li>)}</ol> : <p className="section-note">Your first posted source will start the history.</p>}</section>
  </>;
}
